---

- name: Check if node_exporter is already installed
  stat: path=/usr/local/bin/node_exporter
  register: node_exporter_installed

- name: group prometheus
  group:
    name: "{{prometheus_node_exporter_group}}"
    gid: "{{prometheus_node_exporter_group_gid}}"

- name: user prometheus
  user:
    name: "{{prometheus_node_exporter_user}}"
    uid: "{{prometheus_node_exporter_user_uid}}"
    group: "{{prometheus_node_exporter_group}}"
    shell: /bin/false
    createhome: false

- name: install or update prometheus-node-exporter
  when: not node_exporter_installed.stat.exists or prometheus_node_exporter_reinstall
  block:
    - name: Remove node_exporter archive file if exist
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/{{ prometheus_node_exporter_release_name }}.tar.gz"
        - "/tmp/{{ prometheus_node_exporter_release_name }}"

    - name: Download node_exporter archive
      get_url:
        url: "{{ url }}"
        dest: "/tmp/{{ prometheus_node_exporter_release_name }}.tar.gz"

    - name: Unarchive node_exporter
      unarchive:
        src: "/tmp/{{ prometheus_node_exporter_release_name }}.tar.gz"
        dest: /tmp
        remote_src: true

    - name: Move node_exporter file
      copy:
        remote_src: true
        src: "/tmp//node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ default_architecture }}/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: 0755
      notify:
        - Restart node_exporter

- name: Create node_exporter systemd unit file
  template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service
  notify:
    - Reload node_exporter

- name: Enable and start the exporter
  systemd:
    daemon_reload: true
    name: prometheus-node-exporter
    state: started
    enabled: true
